# PostgreSQL infrastructure setup 

- name: Install postgres 18 on db1 and db2
  hosts:  pitr,db1
  become: yes 
  roles: 
    #  - install_postgres
    #  - postgres_replication 
    #  - prepare_db
       - postgres_pitr