#SPDX-License-Identifier: MIT-0
---
# tasks file for grafana_docker

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create Grafana data directory for persistent data
  ansible.builtin.file:
    path: /var/lib/grafana
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Create Grafana data directory for datasources
  ansible.builtin.file:
    path: /etc/grafana/datasources
    state: directory
    owner: root
    group: root
    mode: '0777'    

- name: Run Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest # Or a specific version, e.g., grafana/grafana:10.4.3
    state: started
    restart_policy: always
    ports:
          - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
          - /var/lib/grafana:/var/lib/grafana                                 # Mount volume for persistent data
          - /etc/grafana/datasources:/etc/grafana/provisioning/datasources
    env:
          GF_SECURITY_ADMIN_USER: admin # Optional: Set admin username
          GF_SECURITY_ADMIN_PASSWORD: grafana # Optional: Set admin password
          

