#SPDX-License-Identifier: MIT-0
---
# tasks file for grafana_docker

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create Grafana data directory for persistent data
  ansible.builtin.file:
    path: "{{ grafana_persitent_data }}"
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Create Grafana data directory for datasources
  ansible.builtin.file:
    path: "{{ dir_datasources }}"
    state: directory
    owner: root
    group: root
    mode: '0777'    

- name: Create Grafana data directory for alerts
  ansible.builtin.file:
    path: "{{ dir_alerting }}"
    state: directory
    owner: root
    group: root
    mode: '0777'     

- name: Copy datasources file
  become: true
  copy:
    src: datasources.yaml
    dest: "{{ dir_datasources }}/datasources.yaml" 
    owner: root
    group: root 
    mode: '0777'

- name: Find files in a directory
  ansible.builtin.find:
    paths: "{{ role_dir }}/files/alerts"        # Specify the directory to search
    file_type: file               # Look for files (not directories)
    recurse: yes                   
    patterns: "alert*"            # Optional: Filter by file extension or pattern
  delegate_to: localhost 
  register: found_files

- name: DEBUG files in directory
  ansible.builtin.debug:
   var: found_files.files

- name: Copy alertconfig file found on previous step
  become: true
  copy:
    src: "{{ item.path }}"
    dest: "{{ dir_alerting }}" 
    owner: root
    group: root
    mode: '0777'   
  loop: "{{ found_files.files }}"
     
- name: Run Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest # Or a specific version, e.g., grafana/grafana:10.4.3
    state: started
    restart_policy: always
    ports:
          - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
          - "{{ grafana_persitent_data }}:/var/lib/grafana"                    # Mount volume for persistent data
          - "{{ dir_datasources }}:/etc/grafana/provisioning/datasources"
          - "{{ dir_alerting }}:/etc/grafana/provisioning/alerting"
    env:
          GF_SECURITY_ADMIN_USER: admin # Optional: Set admin username
          GF_SECURITY_ADMIN_PASSWORD: grafana # Optional: Set admin password
          

