# Firewall setup to filter incoming traffic 

- name: Setup firewall 
  hosts: firewall
  become: yes 
  roles: 
     - iptables_fwd

# - name: Install Node Exporter on host
#   hosts: firewall
#   collections:
#           - prometheus.prometheus
#   roles:
#           - node_exporter