---
- name: Set hostname on target machines
  hosts: pitr
  become: yes 
  tasks:
    
    - name: Set the hostname to inventory_hostname
      shell: hostnamectl set-hostname "{{ inventory_hostname }}"

