router_networks:
  router1:
    - '10.0.12.1/30'
    - '10.0.10.1/30'
    - '172.10.10.2/24'  #Networks to be announced over OSPF

  router2:
    - '10.0.11.2/30'
    - '10.0.10.2/30'
    - '172.10.20.2/24' #Networks to be announced over OSPF 

  router3:
    - '10.0.12.2/30'
    - '10.0.11.1/30'
    - '172.10.30.2/24' #Networks to be announced over OSPF


router_neighbors:
  router1:
    - '10.0.12.2'
    - '10.0.10.2'                        #OSPF neighbors

  router2:
    - '10.0.11.1'
    - '10.0.10.1'                        #OSPF neighbors

  router3:
    - '10.0.12.1'
    - '10.0.11.2'                        #OSPF neighbors
